---
title: "Simulation 65 vs 200"
output: html_document
date: "`r format(Sys.Date(), '%B %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries, include=FALSE}
rm(list=ls())

library(parallel)
cores <- system("nproc", intern=TRUE)

library(dplyr)
library(plyr)
library(tidyr)
library(MASS)
library(Rlab)
library(progress)
library(INLA)
library(brinla)
library(GLMMadaptive)
library(ggpubr)
library(ggplot2)

source("Data_parameters.R")
source("Data_creation.R")
source("models_preparation.R")
source("JMM.R")
source("JSM.R")
source("Ass_coeff_derivation.R")
```

```{r creation of the datasets}
# data_beta_65 <- single.data(65, M)
# save(data_beta_65, file = "data_beta_65.RData")
# data_beta_200 <- single.data(200, M)
# save(data_beta_200, file = "data_beta_200.RData")

load("data_beta_65.RData")    # M datasets with 65 patients
load("data_beta_200.RData")   # M datasets with 200 patients

# checking the creation of the data
ggplot(data = data_beta_200[[2]][[85]], aes(x = t, y = y, group = id)) +
  geom_line() +
  labs(title = "Time trend of y")

ggplot(data = data_beta_200[[2]][[85]], aes(x = t, y = x, group = id)) +
  geom_line() +
  labs(title = "Time trend of x")
```

### Simulation of the JMM

```{r simulations on JMM dataset}
fam <- c("gaussian", "beta")
link_function <- function(x) plogis(x)

# models_JMM_beta_65 <- list("JMM" = list())
# models_JMM_beta_200 <- list("JMM" = list())
# estimation_models(models_JMM_beta_65, data_beta_65, M, FALSE, "JMM")
# estimation_models(models_JMM_beta_200, data_beta_200, M, FALSE, "JMM")

models_JMM_beta_65 <- get(load("models_JMM_beta_65.RData"))     # M JMM models with 65 patients
models_JMM_beta_200 <- get(load("models_JMM_beta_200.RData"))   # M JMM models with 200 patients
```

```{r performance check, warning=FALSE, fig.width=10, fig.height=8}
performance_check_jmmdata <- function(model, type){
  M <- length(model[[type]])
  
  # check the metrics
  tab_info <- cbind("Model" = type,
                    "Marginal Likelihood" = round(mean(ldply(lapply(model[[type]], `[[`, "mlik"))$V1, na.rm = TRUE), 3),
                    "DIC_y" = round(mean(ldply(lapply(model[[type]], `[[`, "y_dic"))$V1, na.rm = TRUE), 3),
                    "DIC_overall" = round(mean(ldply(lapply(model[[type]], `[[`, "overall_dic"))$V1, na.rm = TRUE), 3),
                    "WAIC_y" = round(mean(ldply(lapply(model[[type]], `[[`, "y_waic"))$V1, na.rm = TRUE), 3),
                    "WAIC_overall" = round(mean(ldply(lapply(model[[type]], `[[`, "overall_waic"))$V1, na.rm = TRUE), 3),
                    "CPO_y" = round(mean(ldply(lapply(model[[type]], `[[`, "y_cpo"))$V1, na.rm = TRUE), 3),
                    "CPO_overall" = round(mean(ldply(lapply(model[[type]], `[[`, "overall_cpo"))$V1, na.rm = TRUE), 3))
  
  
  # check the performance plotting the hyperparameters
  real_hyper <- c(1/(sd_x)^2, precision, 1/D_x[1,1], 1/D_y[1,1], 1/D_x[2,2], 1/D_y[2,2], 
                  D[1,3]/(sqrt(D[1,1]*D[3,3])), D[1,2]/(sqrt(D[1,1]*D[2,2])), D[1,4]/(sqrt(D[1,1]*D[4,4])),
                  D[2,3]/(sqrt(D[2,2]*D[3,3])), D[3,4]/(sqrt(D[3,3]*D[4,4])), D[2,4]/(sqrt(D[4,4]*D[2,2])))
  
  names_hyper <- c("Precision of the Gaussian observations",
                   "Precision of the beta observations", 
                   "Precision of random intercepts of v", 
                   "Precision of random intercepts of y", 
                   "Precision of random slopes of v", 
                   "Precision of random slopes of y", 
                   "Correlation random intercepts",
                   "Correlation random effects of v",
                   "Correlation random intercept of v and random slope of y", 
                   "Correlation random intercept of y and random slope of x", 
                   "Correlation random effects of y", 
                   "Correlation random slopes")
  
  plot_data <- list()
  hyperparam_names <- names(model[[type]][[1]]$hyperpar_marginals)
  
  for (i in seq_along(model[[type]])) {
    if(is.na(model[[type]][[i]]$mlik)){next}
    for (hyperparam in hyperparam_names) {
      data <- model[[type]][[i]]$hyperpar_marginals[[hyperparam]]
      x <- data[, 1]
      y <- data[, 2]
      plot_data[[length(plot_data) + 1]] <- data.frame(x = x, y = y, hyperparam = hyperparam, model_id = i)
    }
  }
  
  plot_data <- bind_rows(plot_data)
  plot_data$real <- rep(real_hyper, each = 43)
  plot_data$real_names <- rep(names_hyper, each = 43)
  
  plot <- ggplot(plot_data, aes(x = x, y = y, group = model_id, color = factor(model_id))) +
    geom_line(alpha = 0.2) +
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ real_names, scales = "free", ncol = 2) +
    labs(title = "Distributions of hyperparameters", x = "X-axis", y = "Density", color = "Model ID") +
    theme_minimal() +
    theme(legend.position = "none")
  
  
  # check only the mode of the hyperparameters
  mode_data <- data.frame("mode" = unlist(lapply(model[[type]], 
                                                 function(x) if(sum(is.na(x$precisions)) == 1) {
                                                   rep(NA, nrow(model[[type]][[1]]$precisions))
                                                 } else {x$precisions[, "mode"]})),
                          "var" = rownames(model[[type]][[1]]$precisions))
  mode_data$real <- real_hyper
  mode_data$real_names <- names_hyper
  plot_hist <- ggplot(mode_data, aes(x = mode)) +
    geom_histogram(alpha = 0.7, bins = 50) +
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ real_names, scales = "free", ncol = 2) +
    labs(title = "Histogram of Mode Values - hyperparameters", x = "Mode", y = "Frequency") +
    theme_minimal()
  
  
  # check only the mode of the fixed effects
  mode_data_fix <- data.frame("mode" = unlist(lapply(model[[type]], 
                                                     function(x) if(sum(is.na(x$fix_eff)) == 1) {
                                                       rep(NA, length(model[[type]][[1]]$fix_eff))
                                                     } else {x$fix_eff})),
                              "var" = c("Intercept_x", "time_x", "Intercept_y", "time_y"))
  mode_data_fix$real <- true_betas
  plot_hist_fix <- ggplot(mode_data_fix, aes(x = mode)) +
    geom_histogram(alpha = 0.7, bins = 50) +
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ var, scales = "free", ncol = 2) +
    labs(title = "Histogram of Mode Values - fixed effects", x = "Mode", y = "Frequency") +
    theme_minimal()
  
  return(list("tab_info" = tab_info, "plot" = plot, "hist_hyper" = plot_hist, "hist_fix" = plot_hist_fix))
}

print("The performances of the JMM model with 65 patients are:")
performance_check_jmmdata(models_JMM_beta_65, "JMM")

print("The performances of the JMM modelwith 200 patients are:")
performance_check_jmmdata(models_JMM_beta_200, "JMM")
```

```{r comparison fixed effects 65 vs 200}
mode_jmm <- data.frame("mode" = c(unlist(lapply(models_JMM_beta_65$JMM, 
                                              function(x) if(sum(is.na(x$fix_eff)) == 1) {rep(NA, 4)} else {x$fix_eff})), 
                                  unlist(lapply(models_JMM_beta_200$JMM, 
                                              function(x) if(sum(is.na(x$fix_eff)) == 1) {rep(NA, 4)} else {x$fix_eff}))),
                       "var" = c("Intercept_x", "time_x", "Intercept_y", "time_y"), 
                       "real" = true_betas, 
                       "model" = rep(1:M, each = 4), 
                       "Mode_type" = as.factor(rep(1:2, each = 4*M)))

plot_hist_fix_jmm <- ggplot(mode_jmm, aes(x = mode, fill = Mode_type)) +
    geom_histogram(alpha = 0.7, bins = 50, position = "identity") +
    scale_fill_manual(values = c("#FDB462", "#D95F0E"), labels = c("65", "200")) + 
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ var, scales = "free", ncol = 2) +
    labs(title = "Histogram of Mode Values - fixed effects", x = "Mode", y = "Frequency") +
    theme_light()

plot_hist_fix_jmm
```

```{r comparison hyperparameters 65 vs 200}
var_names <- c("Precision of the Gaussian observations",
                   "Precision of the beta observations", 
                   "Precision of random intercepts of v", 
                   "Precision of random intercepts of y", 
                   "Precision of random slopes of v", 
                   "Precision of random slopes of y", 
                   "Correlation random intercepts",
                   "Correlation random effects of v",
                   "Correlation random intercept of v\nand random slope of y", 
                   "Correlation random intercept of y\nand random slope of v", 
                   "Correlation random effects of y", 
                   "Correlation random slopes")
  
real_values <- c(1/(sd_x)^2, precision, 1/D_x[1,1], 1/D_y[1,1], 1/D_x[2,2], 1/D_y[2,2], 
                          D[1,3]/(sqrt(D[1,1]*D[3,3])), D[1,2]/(sqrt(D[1,1]*D[2,2])), D[1,4]/(sqrt(D[1,1]*D[4,4])),
                          D[2,3]/(sqrt(D[2,2]*D[3,3])), D[3,4]/(sqrt(D[3,3]*D[4,4])), D[2,4]/(sqrt(D[4,4]*D[2,2])))
  
hyper_jmm_old <- data.frame(
    "mode" = c(unlist(lapply(models_JMM_beta_65$JMM, 
                           function(x) if(sum(is.na(x$precisions)) == 1) {
                             rep(NA, nrow(models_JMM_beta_65$JMM[[1]]$precisions))
                             } else {x$precisions[, "mode"]})),
               unlist(lapply(models_JMM_beta_200$JMM, 
                           function(x) if(sum(is.na(x$sds)) == 1) {
                             rep(NA, nrow(models_JMM_beta_200$JMM[[1]]$precisions))
                             } else {x$precisions[, "mode"]}))),
    "var" = var_names,
    "model" = rep(1:M, each = nrow(models_JMM_beta_65$JMM[[1]]$precisions)), 
    "real" = real_values, 
    "source" = as.factor(rep(1:2, each = nrow(models_JMM_beta_65$JMM[[1]]$precisions)*M)))

param_jmm_data <- ggplot(hyper_jmm_old, aes(x = mode, fill = source)) +
    geom_histogram(alpha = 0.7, position = "identity") +
    scale_fill_manual(values = c("#FDB462", "#D95F0E"), labels = c("65", "200")) + 
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ var, scales = "free", ncol = 2) +
    labs(x = "Mode", y = "Frequency", fill = "Number of patients") +
    theme_light() +
    theme(legend.position = "bottom", 
          strip.text = element_text(face = "bold", size = 12, color = "black"))

param_jmm_data

ggsave("param_jmm_data.jpg", plot = param_jmm_data, width = 10, height = 10)
```

```{r}
coeff_dataset_jmm <- data.frame(
    mean = c(
      apply(sapply(models_JMM_beta_65$JMM, function(x) x$coeff_jmm[1, ]), 1, mean, na.rm = TRUE),
      apply(sapply(models_JMM_beta_200$JMM, function(x) x$coeff_jmm[1, ]), 1, mean, na.rm = TRUE),
      coef_jmm
    ),
    quant1 = c(
      apply(sapply(models_JMM_beta_65$JMM, function(x) x$coeff_jmm[1, ]), 1, quantile, prob = 0.05, na.rm = TRUE),
      apply(sapply(models_JMM_beta_200$JMM, function(x) x$coeff_jmm[1, ]), 1, quantile, prob = 0.05, na.rm = TRUE),
      rep(NA, length(time))
    ),
    quant2 = c(
      apply(sapply(models_JMM_beta_65$JMM, function(x) x$coeff_jmm[1, ]), 1, quantile, prob = 0.95, na.rm = TRUE),
      apply(sapply(models_JMM_beta_200$JMM, function(x) x$coeff_jmm[1, ]), 1, quantile, prob = 0.95, na.rm = TRUE),
      rep(NA, length(time))
    ),
    time = time,
    pat = as.factor(rep(c("65", "200", "Real value"), each = length(time))))

plot_jmm_sim <- ggplot(coeff_dataset_jmm, aes(x = time, y = mean)) +
    geom_line(data = subset(coeff_dataset_jmm, pat != "Real value"), aes(color = pat), linewidth = 0.8) +
    geom_line(data = subset(coeff_dataset_jmm, pat == "Real value"), 
              aes(linetype = pat), color = "black", linewidth = 1.2) +
    geom_point(data = subset(coeff_dataset_jmm, pat != "Real value"),
               aes(color = pat), size = 2) +
    geom_ribbon(aes(ymin = quant1, ymax = quant2, fill = pat), alpha = 0.2) +
    labs(x = "Time", 
         y = "Association coefficient", 
         color = "Number of patients",  # Legend for "65" and "200"
         linetype = "Reference") +      # Legend for "Real value"
    scale_color_manual(values = c("65" = "#FDB462", "200" = "#D95F0E")) +
    scale_fill_manual(values = c("65" = "#FDB462", "200" = "#D95F0E"), guide = "none") +
    scale_linetype_manual(values = c("Real value" = "dotted")) +
    guides(color = guide_legend(order = 1), 
           linetype = guide_legend(order = 2), 
           fill = "none") + 
    theme_light() +  
    theme(legend.position = "bottom", 
          legend.direction = "horizontal", 
          # legend.box = "vertical",  # Forces legends to be stacked
          legend.spacing.x = unit(0.7, 'cm'),  
          legend.margin = margin(-5, 0, 0, 0),
          legend.text = element_text(size = 12),       
          legend.title = element_text(size = 13),
          axis.title.x = element_text(size = 13),
          axis.text.x = element_text(size = 12),
          axis.title.y = element_text(size = 13),
          axis.text.y = element_text(size = 12)) +
    scale_x_continuous(breaks = seq(min(coeff_dataset_jmm$time), max(coeff_dataset_jmm$time), by = 2))

plot_jmm_sim

ggsave("jmm_sim_plot.jpg", plot = plot_jmm_sim, width = 7, height = 5)
```

### Simulation of the JSM

```{r simulations on JSM dataset}
# models_JSM_beta_65 <- list("JSM" = list())
# models_JSM_beta_200 <- list("JSM" = list())
# estimation_models(models_JSM_beta_65, data_beta_65, M, FALSE, "JSM")
# estimation_models(models_JSM_beta_200, data_beta_200, M, FALSE, "JSM")

models_JSM_beta_65 <- get(load("models_JSM_beta_65.RData"))     # M JMM models with 65 patients
models_JSM_beta_200 <- get(load("models_JSM_beta_200.RData"))   # M JMM models with 200 patients
```

```{r}
performance_check_jsmdata <- function(model, type){
  M <- length(model[[type]])
  
  # check the metrics
  tab_info <- cbind("Model" = type,
                    "Marginal Likelihood" = round(mean(ldply(lapply(model[[type]], `[[`, "mlik"))$V1, na.rm = TRUE), 3),
                    "DIC_y" = round(mean(ldply(lapply(model[[type]], `[[`, "y_dic"))$V1, na.rm = TRUE), 3),
                    "DIC_overall" = round(mean(ldply(lapply(model[[type]], `[[`, "overall_dic"))$V1, na.rm = TRUE), 3),
                    "WAIC_y" = round(mean(ldply(lapply(model[[type]], `[[`, "y_waic"))$V1, na.rm = TRUE), 3),
                    "WAIC_overall" = round(mean(ldply(lapply(model[[type]], `[[`, "overall_waic"))$V1, na.rm = TRUE), 3),
                    "CPO_y" = round(mean(ldply(lapply(model[[type]], `[[`, "y_cpo"))$V1, na.rm = TRUE), 3),
                    "CPO_overall" = round(mean(ldply(lapply(model[[type]], `[[`, "overall_cpo"))$V1, na.rm = TRUE), 3))
  
  # check the posterior distributions of the hyperparameters
  real_hyper <- c(1/(sd_x^2), precision, 0, 0, 1/D_x[1, 1], 1/D_x[2, 2], D_x[1, 2]/(sqrt(D_x[1, 1])*sqrt(D_x[2, 2])), 
                  1/D_y[1, 1], 1/D_y[2, 2], D_y[1, 2]/(sqrt(D_y[1, 1])*sqrt(D_y[2, 2])), gamma)
  
  names_hyper <- c("Precision of the Gaussian observations",
                   "Precision of the beta observations", 
                   "Precision for fixed intercept x", 
                   "Precision for fixed time x",
                   "Precision of random intercepts of x",
                   "Precision of random slopes of x",
                   "rho random effects x",
                   "Precision of random intercepts of y", 
                   "Precision of random slopes of y", 
                   "rho random effects y", 
                   "Gamma parameter")
  
  plot_data <- list()
  hyperparam_names <- names(model[[type]][[2]]$hyperpar_marginals)
  
  for (i in seq_along(model[[type]])) {
    if(is.na(model[[type]][[i]]$mlik)){next}
    for (hyperparam in hyperparam_names) {
      data <- model[[type]][[i]]$hyperpar_marginals[[hyperparam]]
      x <- data[, 1]
      y <- data[, 2]
      plot_data[[length(plot_data) + 1]] <- data.frame(x = x, y = y, hyperparam = hyperparam, model_id = i)
    }
  }
  
  plot_data <- bind_rows(plot_data)
  plot_data$real <- rep(real_hyper, each = 43)
  plot_data$real_names <- rep(names_hyper, each = 43)
  plot <- ggplot(plot_data, aes(x = x, y = y, group = model_id, color = factor(model_id))) +
    geom_line(alpha = 0.2) +
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ real_names, scales = "free", ncol = 2) +
    labs(title = "Distributions of hyperparameters", x = "X-axis", y = "Density", color = "Model ID") +
    theme_minimal() +
    theme(legend.position = "none")
  
  
  # check only the mode of the hyperparameters
  mode_data <- data.frame("mode" = unlist(lapply(model[[type]], 
                                                 function(x) if(sum(is.na(x$precisions)) == 1) {
                                                   rep(NA, nrow(model[[type]][[1]]$precisions))
                                                   } else {x$precisions[, "mode"]})),
                          "var" = rownames(model[[type]][[1]]$precisions),
                          "real" = real_hyper, 
                          "real_names" = names_hyper)
  plot_hist <- ggplot(mode_data, aes(x = mode)) +
    geom_histogram(alpha = 0.7, bins = 50) +
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ real_names, scales = "free", ncol = 2) +
    labs(title = "Histogram of Mode Values", x = "Mode", y = "Frequency") +
    theme_minimal()
  
  # check only the mode of the fixed effects
  mode_data_fix <- data.frame("mode" = unlist(lapply(model[[type]], 
                                                     function(x) if(sum(is.na(x$fix_eff)) == 1) {
                                                       rep(NA, length(model[[type]][[1]]$fix_eff))
                                                       } else {c(x$fix_eff[1:2], x$fix_eff[3:4] + x$gamma*x$fix_eff[1:2])})),
                          "var" = c("Intercept_x", "time_x", "Intercept_y", "time_y"), 
                          "real" = true_betas)
  plot_hist_fix <- ggplot(mode_data_fix, aes(x = mode)) +
    geom_histogram(alpha = 0.7, bins = 50) +
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ var, scales = "free", ncol = 2) +
    labs(title = "Histogram of Mode Values - fixed effects", x = "Mode", y = "Frequency") +
    theme_minimal()

  return(list("tab_info" = tab_info, "plot" = plot, "hist_hyper" = plot_hist, "hist_fix" = plot_hist_fix))
}

print("The performances of the JMM model with 65 patients are:")
performance_check_jsmdata(models_JSM_beta_65, "JSM")

print("The performances of the JMM model with 200 patients are:")
performance_check_jsmdata(models_JSM_beta_200, "JSM")
```

```{r}
mode_jsm <- data.frame("mode" = c(unlist(lapply(models_JSM_beta_65$JSM, 
                                              function(x) if(sum(is.na(x$fix_eff)) == 1) {
                                                rep(NA, 4)
                                                } else {c(x$fix_eff[1:2], x$fix_eff[3:4] + x$gamma*x$fix_eff[1:2])})),
                                  unlist(lapply(models_JSM_beta_200$JSM, 
                                              function(x) if(sum(is.na(x$fix_eff)) == 1) {
                                                rep(NA, 4)
                                                } else {c(x$fix_eff[1:2], x$fix_eff[3:4] + x$gamma*x$fix_eff[1:2])}))),
                         "var" = c("Intercept_x", "time_x", "Intercept_y", "time_y"), 
                         "real" = true_betas, 
                         "model" = rep(1:M, each = 4), 
                         "Mode_type" = as.factor(rep(1:2, each = 4*M)))
  
plot_hist_fix_jsm <- ggplot(mode_jsm, aes(x = mode, fill = Mode_type)) +
    geom_histogram(alpha = 0.7, bins = 50, position = "identity") +
    scale_fill_manual(values = c("#80B1D3", "#08519c"), labels = c("65", "200")) + 
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ var, scales = "free", ncol = 2) +
    labs(title = "Histogram of Mode Values - fixed effects", x = "Mode", y = "Frequency") +
    theme_light()
  
plot_hist_fix_jsm
```

```{r}
name_jsm_value <- c("Precision of the Gaussian observations",
                   "Precision of the beta observations", 
                   "Precision for fixed intercept v", 
                   "Precision for fixed time v",
                   "Precision of random intercepts of v",
                   "Precision of random slopes of v",
                   "Correlation random effects v",
                   "Precision of random intercepts of y", 
                   "Precision of random slopes of y", 
                   "Correlation random effects y", 
                   "Gamma parameter")

real_jsm_value <- c(1/(sd_x^2), precision, 0, 0, 1/D_x[1, 1], 1/D_x[2, 2], D_x[1, 2]/(sqrt(D_x[1, 1])*sqrt(D_x[2, 2])), 1/D_y[1, 1], 1/D_y[2, 2], 
                    D_y[1, 2]/(sqrt(D_y[1, 1])*sqrt(D_y[2, 2])), gamma)

hyper_jsm_old <- data.frame(
  "mode" = c(unlist(lapply(models_JSM_beta_65$JSM, 
                         function(x) if(sum(is.na(x$precisions)) == 1) {
                           rep(NA, nrow(models_JSM_beta_65$JSM[[1]]$precisions))
                           } else {x$precisions[, "mode"]})), 
             unlist(lapply(models_JSM_beta_200$JSM, 
                         function(x) if(sum(is.na(x$precisions)) == 1) {
                           rep(NA, nrow(models_JSM_beta_200$JSM[[1]]$precisions))
                           } else {x$precisions[, "mode"]}))), 
  "var" = name_jsm_value,
  "model" = rep(1:M, each = nrow(models_JSM_beta_65$JSM[[1]]$precisions)), 
  "real" = real_jsm_value, 
  "source" = as.factor(rep(1:2, each = nrow(models_JSM_beta_65$JSM[[1]]$precisions)*M)))

param_jsm_data <- ggplot(hyper_jsm_old %>%
         filter(var != "Precision for fixed intercept v") %>% 
         filter(var != "Precision for fixed time v"), 
       aes(x = mode, fill = source)) +
    geom_histogram(alpha = 0.7, position = "identity") +
    scale_fill_manual(values = c("#80B1D3", "#08519c"), labels = c("65", "200")) + 
    geom_vline(aes(xintercept = real), linetype = "dashed", color = "black") +
    facet_wrap(~ var, scales = "free", ncol = 2) +
    labs(x = "Mode", y = "Frequency", fill = "Number of patients") +
    theme_light() +
    theme(legend.position = "bottom", 
          strip.text = element_text(face = "bold", size = 12, color = "black"))

param_jsm_data

ggsave("param_jsm_data.jpg", plot = param_jsm_data, width = 10, height = 10)
```

```{r}
coeff_dataset_jsm <- data.frame(
    mean = c(
      apply(sapply(models_JSM_beta_65$JSM, function(x) x$coeff_jsm[1, ]), 1, mean, na.rm = TRUE),
      apply(sapply(models_JSM_beta_200$JSM, function(x) x$coeff_jsm[1, ]), 1, mean, na.rm = TRUE),
      coef_jsm
    ),
    quant1 = c(
      apply(sapply(models_JSM_beta_65$JSM, function(x) x$coeff_jsm[1, ]), 1, quantile, prob = 0.05, na.rm = TRUE),
      apply(sapply(models_JSM_beta_200$JSM, function(x) x$coeff_jsm[1, ]), 1, quantile, prob = 0.05, na.rm = TRUE),
      rep(NA, length(time))
    ),
    quant2 = c(
      apply(sapply(models_JSM_beta_65$JSM, function(x) x$coeff_jsm[1, ]), 1, quantile, prob = 0.95, na.rm = TRUE),
      apply(sapply(models_JSM_beta_200$JSM, function(x) x$coeff_jsm[1, ]), 1, quantile, prob = 0.95, na.rm = TRUE),
      rep(NA, length(time))
    ),
    time = time,
    pat = as.factor(rep(c("65", "200", "Real value"), each = length(time))))

plot_jsm_sim <- ggplot(coeff_dataset_jsm, aes(x = time, y = mean)) +
    geom_line(data = subset(coeff_dataset_jsm, pat != "Real value"), aes(color = pat), linewidth = 0.8) +
    geom_line(data = subset(coeff_dataset_jsm, pat == "Real value"), 
              aes(linetype = pat), color = "black", linewidth = 1.2) +
    geom_point(data = subset(coeff_dataset_jsm, pat != "Real value"),
               aes(color = pat), size = 2) +
    geom_ribbon(aes(ymin = quant1, ymax = quant2, fill = pat), alpha = 0.2) +
    labs(x = "Time", 
         y = "Association coefficient", 
         color = "Number of patients",  # Legend for "65" and "200"
         linetype = "Reference") +      # Legend for "Real value"
    scale_color_manual(values = c("65" = "#80B1D3", "200" = "#08519c" )) +
    scale_fill_manual(values = c("65" = "#80B1D3", "200" = "#08519c"), guide = "none") +
    scale_linetype_manual(values = c("Real value" = "dotted")) +
    guides(color = guide_legend(order = 1), 
           linetype = guide_legend(order = 2), 
           fill = "none") + 
    theme_light() +  
    theme(legend.position = "bottom", 
          legend.direction = "horizontal", 
          # legend.box = "vertical",  # Forces legends to be stacked
          legend.spacing.x = unit(0.7, 'cm'),  
          legend.margin = margin(-5, 0, 0, 0),
          legend.text = element_text(size = 12),       
          legend.title = element_text(size = 13),
          axis.title.x = element_text(size = 13),
          axis.text.x = element_text(size = 12),
          axis.title.y = element_text(size = 13),
          axis.text.y = element_text(size = 12)) +
    scale_x_continuous(breaks = seq(min(coeff_dataset_jsm$time), max(coeff_dataset_jsm$time), by = 2))

plot_jsm_sim

ggsave("jsm_sim_plot.jpg", plot = plot_jsm_sim, width = 7, height = 5)
```



